# Site
name: 'Anantha Raju C'
description: 'Personal Blog'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 'https://anantharajuc.github.io'
disqus: 'anantharajuc'
email: 'arcswdev@gmail.com'
mailchimp-list: 'https://github.us6.list-manage.com/subscribe?u=9c3ebf03f8a30453a21c0b9b8&id=7152e78681'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    anantharajuc:
      name:           Anantha Raju C
      site:           https://anantharajuc.github.io
      avatar:         /assets/images/anantha.jpg
      bio:            "Hi there, i'm Anantha! 👋 I hold a Masters Degree in Computer Science Engineering. Currently i work as a Backend Software Engineer where i primarily work with Java, Spring Boot based Web Applications for products in Customer Engagement domain (Mar-Tech/Ad-Tech). This website began as a pet project and first went online in 2015 and has since undergone a couple of iterations. All the posts here use a minimalist tutorial-style format with images wherever necessary to document a concept/process for myself and acts as a source of quick reference."
      email:          anantharajuc@gmail.com
      twitter:        https://twitter.com/anantharajuc
      instagram:      https://instagram.com/anantharajuc
      github:         https://github.com/AnanthaRajuC
      linkedin:       https://www.linkedin.com/in/anantharajuc
      spotify:        https://open.spotify.com/user/yoi18x6bxdgi7fkirte7lhrvq
      stackoverflow:  https://stackoverflow.com/users/3711562/anantha-raju-c
      goodreads:      https://www.goodreads.com/user/show/49589939-anantha-raju
      soundcloud:     https://soundcloud.com/user-400352466
      quora:          https://www.quora.com/profile/Anantha-Raju-C
      clubhouse:      https://www.clubhouse.com/@anantharajuc
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: anantha
      avatar: /assets/images/anantha.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 25



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]